pipeline:
  identifier: Build_Github_Automation_1691066123217
  name: Build Github-Automation
  orgIdentifier: default
  projectIdentifier: Automation_shellscript
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1672748995711
        repoName: BrendaMohan/Github-Automation
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
